services:
  app:
    build: .
    container_name: nldb
    restart: always
    tty: true
    volumes:
      - ./web:/nldb/web
      - ./config.json:/nldb/config.json
      - /dev/null:/key
      - /dev/null:/cert
    ports:
      - 5050:8080
    depends_on:
      - mongo
      - typesense
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
  typesense:
    image: typesense/typesense:29.0
    restart: always
    volumes:
      - ./typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'